apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-client-secure
  namespace: crdb
spec:
  containers:
  - name: cockroachdb-client-secure
    image: cockroachdb/cockroach:v24.1.3
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach/cockroach-certs/
    command:
    - sleep
    - "2147483648" # 2^31
  terminationGracePeriodSeconds: 300
  volumes:
  - name: client-certs
    projected:
        sources:
          - secret:
              name: cockroachdb-client-secret # Change to {release}-client-secret
              items:
                - key: ca.crt
                  path: ca.crt
                - key: tls.crt
                  path: client.root.crt
                - key: tls.key
                  path: client.root.key
        defaultMode: 256